version: '3'

services:
  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./back:/app/
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: django_user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - ./db:/var/lib/mysql
    ports: 
      - 33306:3306

volumes:
  node-modules-volume: