# Generated by Django 3.1.4 on 2021-05-05 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefecture',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mysite.prefecture'),
        ),
    ]
