# PAY.JP
PAYJP_SECRET_KEY: 'sk_test_65b95dc60106959d1ae11428'
PAYJP_PUBLIC_KEY: 'pk_test_a9264de49ff7e75c7cadbb8e'

# reCAPTCHA
RECAPTCHA_SITE_KEY: '6LevDcsaAAAAAFnU7RFrhIbZ82TYBZGyWLbBNm6v'
RECAPTCHA_SECRET_KEY: '6LevDcsaAAAAAJn1FcS-DcXEsADIB-yQo8aQ-Q6d'

# メール
EMAIL_HOST_USER: 'pykensyo@gmail.com'
EMAIL_HOST_PASSWORD: 'jcxabqrxjnhwkhkk'


